/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#ab2d00",
        "primary-container": "#ff7851",
        "primary-fixed": "#ff7851",
        "primary-fixed-dim": "#ff5d2b",
        "primary-dim": "#962700",
        "on-primary": "#ffefeb",
        "on-primary-container": "#470e00",
        "on-primary-fixed": "#000000",
        "on-primary-fixed-variant": "#581300",
        "inverse-primary": "#ff5722",

        "secondary": "#5c5b5b",
        "secondary-container": "#e5e2e1",
        "secondary-fixed": "#e5e2e1",
        "secondary-fixed-dim": "#d6d4d3",
        "on-secondary": "#ffefeb",
        "on-secondary-container": "#525151",
        "on-secondary-fixed": "#403f3f",
        "on-secondary-fixed-variant": "#5c5b5b",

        "tertiary": "#833e9a",
        "tertiary-container": "#e699fd",
        "tertiary-fixed": "#e699fd",
        "tertiary-fixed-dim": "#d88cee",
        "tertiary-dim": "#76318d",
        "on-tertiary": "#ffedfe",
        "on-tertiary-container": "#570e6f",
        "on-tertiary-fixed": "#360049",

        "error": "#b31b25",
        "error-container": "#fb5151",
        "error-dim": "#9f0519",
        "on-error": "#ffefee",
        "on-error-container": "#570008",

        "background": "#f6f6f6",
        "on-background": "#2d2f2f",
        "surface": "#f6f6f6",
        "surface-dim": "#d3d5d5",
        "surface-bright": "#fefbf7",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f1f1",
        "surface-container": "#e7e8e8",
        "surface-container-high": "#e1e3e3",
        "surface-container-highest": "#dbdddd",
        "surface-tint": "#ab2d00",
        "on-surface": "#2d2f2f",
        "on-surface-variant": "#5a5c5c",
        "inverse-surface": "#0c0f0f",
        "inverse-on-surface": "#9c9d9d",

        "outline": "#767777",
        "outline-variant": "#acadad",
      },
      fontFamily: {
        "display": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "sans": ["Inter", "system-ui", "sans-serif"],
      },
      spacing: {
        "spacing-2": "0.5rem",
        "spacing-4": "1rem",
        "spacing-6": "1.5rem",
        "spacing-8": "2rem",
        "spacing-12": "3rem",
        "spacing-16": "4rem",
      },
      borderRadius: {
        "roundedness-full": "9999px",
        "roundedness-lg": "1rem",
        "roundedness-md": "0.75rem",
      },
    },
  },
  plugins: [],
}
